### ISSUE TITLE
Deleted function

### ISSUE THREAD

**Issue by kunstnet** [dalirnet/vue-sort#1]
Hi,

the setup function is missing after formatting, sample:
https://v3.vuejs.org/guide/composition-api-setup.html#arguments
```<script>
export default {
  props: {},
  setup(props) {}
};
</script>
```
becomes:
```<script>
export default {
  props: {}
};
</script>
```

**Comment by dalirnet** [comment]
Thanks for report. I just update ([v0.0.3](https://github.com/dalirnet/vue-sort/commit/c34515fd912b55656b8702750d8baf7b79fe96d8)) and the `setup` function was added.
